global:

  external_labels:
    cluster: 'r11'
    replica: 'r1'

rule_files:
  - 'alert.rules'
  - './rule/node.rules.yml'
  - './rule/blacker.rules.yml'
  - './rule/bypass.rules.yml'
  - './rule/pd.rules.yml'
  - './rule/tidb.rules.yml'
  - './rule/tikv.rules.yml'
  - './rule/tikv.accelerate.rules.yml'


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - '192.168.230.11:9093'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-1:9090', 'prometheus-2:9090']

  - job_name: "overwritten-nodes"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.230.11:29100'
  - job_name: "tidb"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.230.11:22080'
  - job_name: "tikv"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.230.11:22180'
  - job_name: "pd"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.230.11:22379'
  - job_name: "tidb_port_probe"
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
    - targets:
      - '192.168.230.11:22080'
      labels:
        group: 'tidb'
    - targets:
      - '192.168.230.11:22180'
      labels:
        group: 'tikv'
    - targets:
      - '192.168.230.11:22379'
      labels:
        group: 'pd'
    - targets:
      - '192.168.230.11:23000'
      labels:
        group: 'grafana'
    - targets:
      - '192.168.230.11:29100'
      labels:
        group: 'node_exporter'
    - targets:
      - '192.168.230.11:29115'
      labels:
        group: 'blackbox_exporter'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.230.11:29115
  - job_name: "blackbox_exporter_192.168.230.11:29115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.230.11'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.230.11:29115

  - job_name: 'thanos'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'thanos-sidecar-1:10902'
          - 'thanos-sidecar-2:10902'
          - 'thanos-querier:10902'
          - 'thanos-store-gateway:10902'
          - 'thanos-compactor:10902'
          - 'thanos-ruler:10902'

  - job_name: 'minio'
    scrape_interval: 5s
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/prometheus/metrics

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
